version: "3"
services:
  zilla-frontend:
    image: zilla-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    command: ["npm", "run", "start"]
